### ISSUE TITLE
TrackPoint sometime don't work

### ISSUE THREAD

**Issue by ISouthRain** [infused-kim/kb_zmk_ps2_mouse_trackpoint_driver#4]
My keyboard:
nice_nano_v2
Corne
TrackPoint: X250
config source: https://github.com/infused-kim/kb_zmk_ps2_mouse_trackpoint_driver-zmk_config/
    SCL: D16
    SDA: D10
    Power-On-Reset: D9

Q1: TrackPoint sometime don't work, touch TrackPoint no response, wait a long time, maybe a few minutes, and it works again, 
      Especially when you touch TrackPoint when you first start the keyboard, TrackPoint will no longer be available and you must          restart the keyboard to restore it.

Q2: After moving the TrackPoint, it remains in the TP layer, even if I move away from the TrackPoint, I have to restart the keyboard to recover

These two questions are very frequent.
This makes me feel like TrackPoint is not working properly at all, I was wondering what your experience was like?

**Comment by infused-kim** [comment]
The first thing I would check is the soldering. Maybe you have a bad connection somewhere?

And then I would analyse the logs. Check out the trouble shooting section in the readme.

**Comment by ISouthRain** [comment]
Is it because my welding wire is too small?

**Comment by ISouthRain** [comment]
> The first thing I would check is the soldering. Maybe you have a bad connection somewhere?
> 
> And then I would analyse the logs. Check out the trouble shooting section in the readme.

In readme no record.
I want to know what's the problem
USB Log:         
```shell
00:01:34.704,254] [1;31m<err> zmk: PS/2 Mouse cmd buffer is out of aligment. Requesting resend: Bit 3 of packet is 0 instead of 1[0m
[00:01:34.707,550] [1;33m<wrn> ps2_uart: UART RX detected error for byte 0x38: Framing error (4)[0m
[00:01:34.707,641] [1;31m<err> zmk: PS/2 Mouse cmd buffer is out of aligment. Requesting resend: Bit 3 of packet is 0 instead of 1[0m
[00:01:34.711,029] [1;33m<wrn> ps2_uart: UART RX detected error for byte 0x38: Framing error (4)[0m
[00:01:34.711,120] [1;31m<err> zmk: PS/2 Mouse cmd buffer is out of aligment. Requesting resend: Bit 3 of packet is 0 instead of 1[0m
[00:01:34.714,477] [1;33m<wrn> ps2_uart: UART RX detected error for byte 0x38: Framing error (4)[0m  
```

**Comment by infused-kim** [comment]
The readme has an entire section on how to troubleshoot with a lot of advice on what to try. 

The first thing you should try is re-solder the connections. 

This trackpoint is known to work well. And based on what you provided, I don’t have enough information to conclude it’s a bug in the driver. 

Therefore I’m going to close the issue. 

I’m sorry, but I can’t afford to provide extensive hardware debugging support for free.
