### ISSUE TITLE
Joystick support

### ISSUE THREAD

**Issue by YaphethSN** [infused-kim/kb_zmk_ps2_mouse_trackpoint_driver#7]
hello! was wondering for the diagram of this keyboard if i decided to replace the trackpoint with a joystick on a wireless corne using a nrf52, or is that not possible?

**Comment by infused-kim** [comment]
It’s probably not possible unless you find a joystick that uses the PS/2 mouse protocol. Then it might work, but you have to look at the data sheet of the joystick on how to wire it up.
