### ISSUE TITLE
[Question]  ICSH044A connectivity 

### ISSUE THREAD

**Issue by LeFFaQ** [infused-kim/kb_zmk_ps2_mouse_trackpoint_driver#9]
Hi! I have a question about  [ICSH044A trackball](https://aliexpress.ru/item/32914665887.html?sku_id=65920199762&spm=a2g2w.productlist.search_results.0.5a253d9djp87aN) connectivity. This module does not support SPI. The only connection method I can think of is to connect each pin to a key matrix of columns and rows and set their behavior to ```&mmv MOVE_XXXX```. Will this work the way I am suggesting? I will be using the high frequency pins of my pro micro for the connection.
 
There is example of what im trying to do:
```
     | Column 1 | Column 2 | Column 3 |
     |----------|----------|----------|
Row 1|   none   |  pin UP  |   none   |
Row 2|  pin LFT |  pin CTR |  pin RHT |
Row 3|   none   |  pin DW  |   none   |
```
This snippet will be in existing col-row layout of my keyboard.

**Comment by infused-kim** [comment]
Hi,

I am sorry, but I have no idea about trackballs. This repo is only for PS/2 devices like TrackPoints.

Greetings, Kim
